name: srm_exam_x
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  animations: ^2.0.11
  carousel_slider: ^5.0.0
  file_picker: ^8.3.2
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/srm_logo.png
    - assets/srm.png
    - assets/ok.png
    - assets/icon.png 
    - assets/notice.jpeg 
    - assets/srm_2.png
    - assets/srm_3.png
    - assets/ban.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/icon.png"
