// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlV0lKT1pLC5nEcHuc0nC6twiBZTaXU3I',
    appId: '1:686267504344:web:21f7902b5d6c5ccc65a9ad',
    messagingSenderId: '686267504344',
    projectId: 'srmpyq-b50ed',
    authDomain: 'srmpyq-b50ed.firebaseapp.com',
    storageBucket: 'srmpyq-b50ed.firebasestorage.app',
    measurementId: 'G-HC3C9MB4EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5Hz9OEAVUPKg6aEJbnzwgwmCCtvqLBQ',
    appId: '1:686267504344:android:615b3ebd2be2f8a565a9ad',
    messagingSenderId: '686267504344',
    projectId: 'srmpyq-b50ed',
    storageBucket: 'srmpyq-b50ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQp9q-KvyOjIYZOxIh2vvYd4bgycTwlx8',
    appId: '1:686267504344:ios:40085febb48642c365a9ad',
    messagingSenderId: '686267504344',
    projectId: 'srmpyq-b50ed',
    storageBucket: 'srmpyq-b50ed.firebasestorage.app',
    iosClientId: '686267504344-9bcct5cvm64b28pn5ca7erfvi80ta7b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.srmone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQp9q-KvyOjIYZOxIh2vvYd4bgycTwlx8',
    appId: '1:686267504344:ios:40085febb48642c365a9ad',
    messagingSenderId: '686267504344',
    projectId: 'srmpyq-b50ed',
    storageBucket: 'srmpyq-b50ed.firebasestorage.app',
    iosClientId: '686267504344-9bcct5cvm64b28pn5ca7erfvi80ta7b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.srmone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlV0lKT1pLC5nEcHuc0nC6twiBZTaXU3I',
    appId: '1:686267504344:web:23312e5b0500869665a9ad',
    messagingSenderId: '686267504344',
    projectId: 'srmpyq-b50ed',
    authDomain: 'srmpyq-b50ed.firebaseapp.com',
    storageBucket: 'srmpyq-b50ed.firebasestorage.app',
    measurementId: 'G-GR729H0Y3P',
  );
}
